export type UserRole =
  | "ALU_REG"
  | "FAM_APO"
  | "STF_PROF"
  | "DIR_TES_APO"
  | "DIR_SEC_APO"
  | "DIR_PRES_APO"
  | "STF_DIR"
  | "administrador"
  | "DIR_TES_ALU"
  | "DIR_SEC_ALU"
  | "DIR_PRES_ALU"
  | "CEN_PRES_CAL"
  | "CEN_TES_CAL"
  | "CEN_SEC_CAL"
  | "CEN_PRES_CAP"
  | "CEN_TES_CAP"
  | "CEN_SEC_CAP";
